name: udbd
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  equatable: ^2.0.5
  fluent_ui: ^4.8.7
  flutter:
    sdk: flutter
  flutter_acrylic: ^1.1.3
  flutter_bloc: ^8.1.5
  flutter_linkify: ^6.0.0
  get_it: ^7.6.7
  go_router: ^14.1.3
  intl: ^0.18.1
  postgres: ^3.2.1
  system_theme: ^2.3.1
  url_launcher: ^6.2.6
  window_manager: ^0.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
